### ISSUE TITLE
Error when trying to create a policy with no port specified

### ISSUE THREAD

**Issue by MrTrustor** [GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang#23]
With release 0.3-rc1, I cannot create a FQDNNetworkpolicy that doesn't have a port specified:

```
$ kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang/main/config/samples/networking_v1alpha3_fqdnnetworkpolicy_valid_noport.yaml
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang/main/config/samples/networking_v1alpha3_fqdnnetworkpolicy_valid_noport.yaml": Internal error occurred: failed calling webhook "vfqdnnetworkpolicy.kb.io": failed to call webhook: Post "https://fqdnnetworkpolicies-webhook-service.fqdnnetworkpolicies-system.svc:443/validate-networking-gke-io-v1alpha3-fqdnnetworkpolicy?timeout=10s": EOF
```

The logs of the manager contain the following error:

```
1.6611897476732416e+09  INFO    fqdnnetworkpolicy-resource      validate create {"name": "fqdnnetworkpolicy-valid-noport"}
2022/08/22 17:35:47 http: panic serving 10.48.0.3:52170: runtime error: invalid memory address or nil pointer dereference
goroutine 464 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x153c5e0, 0x24120d0})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang/api/v1alpha3.(*FQDNNetworkPolicy).ValidatePorts(0xc00003ce00)
        /workspace/api/v1alpha3/fqdnnetworkpolicy_webhook.go:135 +0xf09
github.com/GoogleCloudPlatform/gke-fqdnnetworkpolicies-golang/api/v1alpha3.(*FQDNNetworkPolicy).ValidateCreate(0xc00003ce00)
        /workspace/api/v1alpha3/fqdnnetworkpolicy_webhook.go:92 +0xd9
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*validatingHandler).Handle(_, {_, _}, {{{0xc000314c30, 0x24}, {{0xc00052ef00, 0x11}, {0xc0005c6240, 0x8}, {0xc00052ef18, ...}}, ...}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/webhook/admission/validator.go:71 +0x239
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc000314c30, 0x24}, {{0xc00052ef00, 0x11}, {0xc0005c6240, 0x8}, {0xc00052ef18, ...}}, ...}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/webhook/admission/webhook.go:146 +0xa2
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc000023600, {0x7fc1f340b5b8?, 0xc0002c1e00}, 0xc00065fe00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/webhook/admission/http.go:98 +0xe90
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7fc1f340b5b8, 0xc0002c1e00}, 0x194c700?)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/promhttp/instrument_server.go:40 +0xd4
net/http.HandlerFunc.ServeHTTP(0x194c720?, {0x7fc1f340b5b8?, 0xc0002c1e00?}, 0xc000749a38?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x194c720?, 0xc00057c9a0?}, 0xc00065fe00)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/promhttp/instrument_server.go:117 +0xaa
net/http.HandlerFunc.ServeHTTP(0x2434460?, {0x194c720?, 0xc00057c9a0?}, 0xc0007499c0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x194c720, 0xc00057c9a0}, 0xc00065fe00)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/promhttp/instrument_server.go:84 +0xbf
net/http.HandlerFunc.ServeHTTP(0x1cb18523ea?, {0x194c720?, 0xc00057c9a0?}, 0xc0000ecb80?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc000661edc?, {0x194c720, 0xc00057c9a0}, 0xc00065fe00)
        /usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x19401f8?}, {0x194c720, 0xc00057c9a0}, 0xc00065fe00)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0003e80a0, {0x194d2e0, 0xc0003807e0})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db
```

**Comment by MrTrustor** [comment]
Closing because of release of new official GKE feature: https://cloud.google.com/kubernetes-engine/docs/how-to/fqdn-network-policies
